SWE_project/SWE_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView 

urlpatterns = [
    #path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

SWE_project/accounts/urls.py
# -*- coding: utf-8 -*-
"""
Created on Sun May 23 12:41:22 2021

@author: Perhaps
"""

from django.urls import path

#from .views import SignUpView, PasswordReset
from .views import PasswordReset
from .views import *


urlpatterns = [
    #path('signup/', SignUpView.as_view(), name='signup'),
    path('signup/', signup, name='signup'),
    path('store_signup/', store_signup, name='store_signup'),
    #path('search_stores/', SearchBar.as_view(), name='search_stores'),
    path('search_stores/', search_stores_view, name='search_stores'),
    path('profile/', profile_view, name='profile'),
    path('ckeck_availability/<store_name>', check_availability_view, name='check_availability'),
    path('make_appointment/<store_name>', make_appointment_view, name='make_appointment'),
    path('show_profile/<store_name>', show_profile_view, name='show_profile'),
    path('favourites/', favourites_view, name='favourites'),
    path('add_to_favourites/<store_id>', add_to_favourites_view, name='add_to_favourites'),
    #path('signup/', home_view, name='signup'),
    path('password_reset_form/', PasswordReset.as_view(), name='password_reset_form'),
]

SWE_project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

class SignUpForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    #is_store = forms.BooleanField(help_text='Required')

    class Meta:
        model = User
        widgets = {
            'email': forms.TextInput(attrs={'class': 'input-group mb-2 d-flex justify-content-center form_container'}),
            'username': forms.TextInput(attrs={'class': 'input-group mb-2 d-flex justify-content-center form_container'}),
            'password1': forms.TextInput(attrs={'class': 'input-group mb-2 d-flex justify-content-center form_container'}),
            'password2': forms.TextInput(attrs={'class': 'input-group mb-2 d-flex justify-content-center form_container'}),
            'birth_date': forms.TextInput(attrs={'class': 'input-group mb-3 d-flex justify-content-center form_container'}),
            }
        fields = ('email', 'username', 'birth_date', 'password1', 'password2',)# 'is_active')

class StoreSignUpForm(UserCreationForm):
    #birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    #is_store = forms.BooleanField(help_text='Required')
    store_name = forms.CharField(help_text='Required. This is your store\'s name.', required=True)
    
    class Meta:
        model = User
        fields = ('store_name', 'email', 'username', 'password1', 'password2', )

class StoreSearchForm(forms.ModelForm):
    search_box = forms.CharField(help_text='Input the store name here.', label='searched')
    
    class Meta:
        model = Search_bar_model
        widgets = {
            'search_box': forms.TextInput(attrs={'class': 'myclass'}),
            }
        fields = ['search_box', ]

class MakeAppointment(forms.ModelForm):  
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    
    class Meta:
        model = Make_appointment_model
        fields = ['date', ]

SWE_project/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Generic Title{% endblock %}</title>
  {% block scripts %} {% endblock %}
  {% block styles %} {% endblock %}
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
	{% block bodyscripts %}
	{% endblock %}
</body>
</html>

SWE_project/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block scripts %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">
{% endblock %}

{% block styles %}
	<style>
      body {
        background-image: linear-gradient(to right, mediumpurple,Plum);
      }

      .form-div{
        background-color: lightgrey;
        position: relative;
        left:  300px;
        top:  -250px;
        padding: 10px 15px 5px 35px; 
        border: 1px solid pink;
        border-radius: 5px;
        font-size: 1.1em;
      }

      .logo {
        position: relative;
        left:  40px;
        bottom:  -250px;
      }

      .image {
       position: relative;
       left: -200px;

      }

      .title {
        position: relative;
        left: 50px;
      }

		.myclass {
		  background-color: #4CAF50;
		  background-image: linear-gradient(to left, mediumpurple, green);
		  border: none;
		  color: white;
		  padding: 16px 32px;
		  text-decoration: none;
		  margin: 4px 2px;
		  cursor: pointer;
		}
  </style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class='container'>
	<div class="logo">
		<h1>Hairointment</h1>
		<h3>The look you want for less...</h3>
	</div>
	<div class="image">
		{% load static %}
		<img src="{% static '/images/air2.png' %}" alt="air">
	</div>
	<div class="row">
		<div class="col-md-4 offset-md-4 form-div login">
			<form>
				<div class="title">
					<h3> Γειά σου, {{ user.username }}! </h3>
				</div>
				<div class='form-group'>
				  <p><a href="{% url 'logout' %}">Log Out</a></p>
				  <p><a href="{% url 'profile' %}">Προφίλ</a></p>
				  <p><a href="{% url 'search_stores' %}">Αναζήτηση καταστημάτων</a></p>
				</div>
			</form>
		</div>
	</div>
</div>
  Γειά σου {{ user.username }}!

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'signup' %}">Εγγραφή χρήστη</a>
  <a href="{% url 'store_signup' %}">Εγγραφή καταστήματος</a>
  <a href="{% url 'password_reset' %}">Password Reset</a>
{% endif %}
{% endblock %}

SWE_project/templates/make_appointment.html
<!-- templates/make_appointments.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block scripts %}
	<!-- jQuery -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	<!-- XDSoft DateTimePicker -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">

{% endblock %}

{% block styles %}
	<style>
      body {
        background-image: linear-gradient(to right, mediumpurple,Plum);
      }

      .form-div{
        background-color: lightgrey;
        position: relative;
        left:  300px;
        top:  -250px;
        padding: 10px 15px 5px 35px; 
        border: 1px solid pink;
        border-radius: 5px;
        font-size: 1.1em;
      }

      .logo {
        position: relative;
        left:  40px;
        bottom:  -250px;
      }

      .image {
       position: relative;
       left: -200px;

      }

      .title {
        position: relative;
        left: 50px;
      }
  </style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class='container'>
	<div class="logo">
		<h1>Hairointment</h1>
		<h3>The look you want for less...</h3>
	</div>
	<div class="image">
		{% load static %}
		<img src="{% static '/images/air2.png' %}" alt="air">
	</div>
	<div class="row">
		<div class="col-md-4 offset-md-4 form-div login">
			<form>
				<div class="title">
					<h3> Γειά σου, {{ user.username }}! </h3>
				</div>
				<div class='form-group'>
				<h2> Κλείσε ραντεβού στο {{ st_name }} </h2>
					<form method="post" action="{% url 'check_availability' st_name %}">
						{% csrf_token %}
						<p> Ημέρα και ώρα του ραντεβού: </p>
						<p> {{ form.date }} </p>
						<br/>
						<p> Messages: {{ msg }} </p>
						<br/>
						<Button type="submit"> Κλείσε ραντεβού </Button>
					</form>
				</div>
				<div class='form-group'>
					<p><a href="{% url 'logout' %}">Log Out</a></p>
					<p><a href="{% url 'search_stores' %}">Αναζήτηση καταστημάτων</a></p>
				</div>
			</form>
		</div>
	</div>
</div>
  
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

{% block bodyscripts %}
	<script>
		window.ready = $(function () {
			$("#id_date").datetimepicker();
			console.log('Fired');
		});
	</script>

{% endblock %}

SWE_project/templates/profile.html
<!-- templates/profile.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block scripts %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">
{% endblock %}

{% block styles %}
	<style>
      body {
        background-image: linear-gradient(to right, mediumpurple,Plum);
      }

      .form-div{
        background-color: lightgrey;
        position: relative;
        left:  300px;
        top:  -250px;
        padding: 10px 15px 5px 35px; 
        border: 1px solid pink;
        border-radius: 5px;
        font-size: 1.1em;
      }

      .logo {
        position: relative;
        left:  40px;
        bottom:  -250px;
      }

      .image {
       position: relative;
       left: -200px;

      }

      .title {
        position: relative;
        left: 50px;
      }

		.myclass {
		  background-color: #4CAF50;
		  background-image: linear-gradient(to left, mediumpurple, green);
		  border: none;
		  color: white;
		  padding: 16px 32px;
		  text-decoration: none;
		  margin: 4px 2px;
		  cursor: pointer;
		}
  </style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class='container'>
	<div class="logo">
		<h1>Hairointment</h1>
		<h3>The look you want for less...</h3>
	</div>
	<div class="image">
		{% load static %}
		<img src="{% static '/images/air2.png' %}" alt="air">
	</div>
	<div class="row">
		<div class="col-md-4 offset-md-4 form-div login">
			<form>
				<div class="title">
					<h3> Γειά σου, {{ user.username }}! </h3>
				</div>
				<div class='form-group'>
					<h2> Το Προφίλ σου </h2>
					<p> 
						<label> username: {{ user }} </label> 
						<br/>
						<label> email: {{ user.email }} </label>
						<br/>
						<label> Όνομα καταστήματος: {{ store_name }} </label> 
						<br/>
						<label> last login: {{ last_login }} </label>
						<br/>
						<label> date joined: {{ date_joined }} </label>
						<br/>
					</p>
				</div>
				<div class='form-group'>
				  <p><a href="{% url 'logout' %}">Log Out</a></p>
				  <p><a href="{% url 'password_reset' %}">Password Reset</a></p>
				  <p><a href="{% url 'search_stores' %}">Αναζήτηση καταστημάτων</a></p>
				  <p><a href="{% url 'favourites' %}">Αγαπημένα</a></p>
				</div>
			</form>
		</div>
	</div>
</div>
    
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

SWE_project/templates/search_stores.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block scripts %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">
{% endblock %}

{% block styles %}
	<style>
      body {
        background-image: linear-gradient(to right, mediumpurple,Plum);
      }

      .form-div{
        background-color: lightgrey;
        position: relative;
        left:  300px;
        top:  -250px;
        padding: 10px 15px 5px 35px; 
        border: 1px solid pink;
        border-radius: 5px;
        font-size: 1.1em;
      }

      .logo {
        position: relative;
        left:  40px;
        bottom:  -250px;
      }

      .image {
       position: relative;
       left: -200px;

      }

      .title {
        position: relative;
        left: 50px;
      }

		.myclass {
		  background-color: #4CAF50;
		  background-image: linear-gradient(to left, mediumpurple, green);
		  border: none;
		  color: white;
		  padding: 16px 32px;
		  text-decoration: none;
		  margin: 4px 2px;
		  cursor: pointer;
		}
  </style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <div class='container'>
        <div class="logo">
        <h1>Hairointment</h1>
        <h3>The look you want for less...</h3>
      </div>
      <div class="image">
        {% load static %}
        <img src="{% static '/images/air2.png' %}" alt="air">
      </div>
	  <div class="row">
      <div class="col-md-4 offset-md-4 form-div login">
		<form method="post" action="{% url 'search_stores' %}">
		    <div class="title">
				<h3> Γειά σου, {{ user.username }}! </h3>
			</div>
			<div class='form-group'>
			<p>Αναζήτηση καταστήματος...</p>
			{% csrf_token %}
			{{ form.as_p }}
			</div>
			<Button type="submit"> Submit </Button>
			<br/>
			<div class='form-group'>
			{% if stores %}
				<h1>Βρέθηκαν:</h1>
				<div>
					{% for store in stores %}
						<a href="{% url 'show_profile' store.store_name %}"> {{ store }} </a>
						<br/>
					{% endfor %}
				</div>
			{% else %}
				<h1>Δε βρέθηκαν καταστήματα</h1>
			{% endif %}
			</div>
			<div class='form-group'>
				<p><a href="{% url 'logout' %}">Log Out</a></p>
				<p><a href="{% url 'profile' %}">Προφίλ</a></p>
			</div>
		</form>
		</div>
		</div>

  </div>
  </div>
  </div>
  

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'signup' %}">Sign Up</a>
  <a href="{% url 'store_signup' %}">Store Sign Up</a>
  <a href="{% url 'password_reset' %}">Password Reset</a>
{% endif %}
{% endblock %}

SWE_project/templates/show_favourites.html
<!-- templates/show_profile.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block scripts %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">
{% endblock %}

{% block styles %}
	<style>
      body {
        background-image: linear-gradient(to right, mediumpurple,Plum);
      }

      .form-div{
        background-color: lightgrey;
        position: relative;
        left:  300px;
        top:  -250px;
        padding: 10px 15px 5px 35px; 
        border: 1px solid pink;
        border-radius: 5px;
        font-size: 1.1em;
      }

      .logo {
        position: relative;
        left:  40px;
        bottom:  -250px;
      }

      .image {
       position: relative;
       left: -200px;

      }

      .title {
        position: relative;
        left: 50px;
      }

		.myclass {
		  background-color: #4CAF50;
		  background-image: linear-gradient(to left, mediumpurple, green);
		  border: none;
		  color: white;
		  padding: 16px 32px;
		  text-decoration: none;
		  margin: 4px 2px;
		  cursor: pointer;
		}
  </style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class='container'>
	<div class="logo">
		<h1>Hairointment</h1>
		<h3>The look you want for less...</h3>
	</div>
	<div class="image">
		{% load static %}
		<img src="{% static '/images/air2.png' %}" alt="air">
	</div>
	<div class="row">
		<div class="col-md-4 offset-md-4 form-div login">
			<form>
				<div class="title">
					<h3> Γειά σου, {{ user.username }}! </h3>
				</div>
				<div class='form-group'>
					<h2> Αγαπημένα </h2>
					<p>
						{% for fav in favs.values %}
							{{fav}}
						{% endfor %}
					</p>
				</div>
				<div class='form-group'>
					<p><a href="{% url 'logout' %}">Log Out</a></p>
					<p><a href="{% url 'search_stores' %}">Προσθήκη στα αγαπημένα</a></p>
				</div>
			</form>
		</div>
	</div>
</div>
  
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

SWE_project/templates/show_profile.html
<!-- templates/show_profile.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block scripts %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">
{% endblock %}

{% block styles %}
	<style>
      body {
        background-image: linear-gradient(to right, mediumpurple,Plum);
      }

      .form-div{
        background-color: lightgrey;
        position: relative;
        left:  300px;
        top:  -250px;
        padding: 10px 15px 5px 35px; 
        border: 1px solid pink;
        border-radius: 5px;
        font-size: 1.1em;
      }

      .logo {
        position: relative;
        left:  40px;
        bottom:  -250px;
      }

      .image {
       position: relative;
       left: -200px;

      }

      .title {
        position: relative;
        left: 50px;
      }

		.myclass {
		  background-color: #4CAF50;
		  background-image: linear-gradient(to left, mediumpurple, green);
		  border: none;
		  color: white;
		  padding: 16px 32px;
		  text-decoration: none;
		  margin: 4px 2px;
		  cursor: pointer;
		}
  </style>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class='container'>
	<div class="logo">
		<h1>Hairointment</h1>
		<h3>The look you want for less...</h3>
	</div>
	<div class="image">
		{% load static %}
		<img src="{% static '/images/air2.png' %}" alt="air">
	</div>
	<div class="row">
		<div class="col-md-4 offset-md-4 form-div login">
			<form>
				<div class="title">
					<h3> Γειά σου, {{ user.username }}! </h3>
				</div>
				<div class='form-group'>
					<h2> Προφίλ καταστήματος </h2>
					<p> 
						<label> username: {{ st_username }} </label> 
						<br/>
						<label> email: {{ st_email }} </label>
						<br/>
						<label> Όνομα καταστήματος: {{ store_name }} </label> 
						<br/>
						<label> last login: {{ st_last_login }} </label>
						<br/>
						<label> date joined: {{ st_date_joined }} </label>
						<br/>
					</p>
				</div>
				<div class='form-group'>
				  <p><a href="{% url 'logout' %}">Log Out</a></p>
				  <p><a href="{% url 'make_appointment' store_name %}">Κλείσε ραντεβού</a></p>
				  <p><a href="{% url 'add_to_favourites' st_id %}">Προσθήκη στα αγαπημένα</a></p>
				  <p><a href="{% url 'password_reset' %}">Password Reset</a></p>
				  <p><a href="{% url 'search_stores' %}">Αναζήτηση καταστημάτων</a></p>
				</div>
			</form>
		</div>
	</div>
</div>
  
  
  

  
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}